server:
  port: ${SERVER_PORT:8091}

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:habitsystem}
    password: ${SPRING_DATASOURCE_PASSWORD:habitsystem}
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 5
      minimumIdle: 2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/auth
    validate-on-migrate: true
    clean-disabled: true
    schemas: public
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      properties:
        delivery.timeout.ms: 120000
        retry.backoff.ms: 1000
        max.block.ms: 60000
        request.timeout.ms: 30000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 10000
        acks: all
        batch.size: 16384
        linger.ms: 100
        buffer.memory: 33554432
        spring.json.add.type.headers: true
        spring.json.trusted.packages: "com.habitsystem.auth.event"

logging:
  level:
    org.springframework.security: DEBUG
    com.habitsystem.auth: DEBUG
    org.springframework.web: DEBUG
    net.devh.boot.grpc: DEBUG
    com.habitsystem: DEBUG

grpc:
  server:
    port: 9091
    address: 0.0.0.0
    security:
      enabled: false
  client:
    user-service:
      address: static://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:9092}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      keepAliveTime: 30s
      keepAliveTimeout: 5s
      idleTimeout: 300s
      deadlineInSeconds: 5

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-that-should-be-very-long-and-secure}
  access-token:
    expiration: 60
  refresh-token:
    expiration: 10080

verification:
  token:
    expiration: 1440

rate:
  limit:
    max-requests: 60
    window-minutes: 1

security:
  public-paths:
    - /api/v1/auth/register
    - /api/v1/auth/login
    - /api/v1/auth/verify
    - /api/v1/auth/refresh
    - /actuator/**
