server:
  port: ${SERVER_PORT:8091}

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:habitsystem}
    password: ${SPRING_DATASOURCE_PASSWORD:habitsystem}
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      minimumIdle: 5
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      initialization-fail-timeout: 60000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: auth-tx-
      properties:
        enable.idempotence: true
        acks: all
        retries: 10
        max.in.flight.requests.per.connection: 1
        delivery.timeout.ms: 120000

logging:
  level:
    org.springframework.security: DEBUG
    com.habitsystem.auth: DEBUG
    org.springframework.web: DEBUG
    net.devh.boot.grpc: DEBUG
    com.habitsystem: DEBUG
    org.flywaydb: DEBUG

grpc:
  server:
    port: 9091
    address: 0.0.0.0
    security:
      enabled: false
  client:
    user-service:
      address: static://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:9092}
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      keepAliveTime: 30s
      keepAliveTimeout: 5s
      idleTimeout: 300s
      deadlineInSeconds: 5

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-that-should-be-very-long-and-secure}
  access-token:
    expiration: 60
  refresh-token:
    expiration: 10080

verification:
  token:
    expiration: 1440

rate:
  limit:
    max-requests: 60
    window-minutes: 1

security:
  public-paths:
    - /api/v1/auth/register
    - /api/v1/auth/login
    - /api/v1/auth/verify
    - /api/v1/auth/refresh
    - /actuator/**

application:
  security:
    suspicious-domain:
      threshold: 5
      window-minutes: 60
    cleanup-interval-ms: 600000

kafka:
  topics:
    suspicious-domains: suspicious-domains
