server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - RequestTransformation
        - RateLimiting
      routes:
        - id: auth-service
          uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8091}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - PreserveHostHeader
        - id: user-service
          uri: http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8092}
          predicates:
            - Path=/api/users/**
          filters:
            - PreserveHostHeader
        - id: habit-service
          uri: http://${HABIT_SERVICE_HOST:localhost}:${HABIT_SERVICE_PORT:8095}
          predicates:
            - Path=/api/habits/**
          filters:
            - PreserveHostHeader
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200" # frontend app
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
