server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - RequestTransformation
        - RateLimiting
      routes:
        - id: auth-service
          uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8091}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - PreserveHostHeader
        - id: user_service
          uri: grpc://user-service:9092  # Change from HTTP to gRPC
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
            - Authentication
            - name: GrpcRouting
              args:
                serviceClass: com.habitsystem.proto.user.UserServiceGrpc
                requestClass: com.habitsystem.proto.user.UserRequest
                responseClass: com.habitsystem.proto.user.UserResponse
        - id: habit-service
          uri: grpc://localhost:9093
          predicates:
            - Path=/api/habits/**
          filters:
            - StripPrefix=2
            - Authentication
            - name: GrpcRouting
              args:
                serviceClass: com.habitsystem.proto.habit.HabitServiceGrpc
                requestClass: com.habitsystem.proto.habit.HabitRequest
                responseClass: com.habitsystem.proto.habit.HabitResponse
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

grpc:
  client:
    auth-service:
      address: static://auth-service:9091  # gRPC port for auth-service
      negotiationType: PLAINTEXT
    user-service:
      address: static://user-service:9092  # gRPC port for user-service
      negotiationType: PLAINTEXT
    habit-service:
      address: static://localhost:9093
      negotiationType: PLAINTEXT

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
