spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: habitsystem
    password: habitsystem
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 60000
